version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NEXT_PUBLIC_BASE_URL=http://localhost:3000
    ports:
      - '3000:3000'

  cypress:
    image: cypress/included:13.17.0
    depends_on:
      - app
    environment:
      - CYPRESS_BASE_URL=http://app:3000
    volumes:
      - ./:/e2e
    working_dir: /e2e
    entrypoint: sh -c "npm install && npx cypress run"
